package com.example.spba.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
public class WalletHistory {
    @TableId(type = IdType.AUTO)
    private Integer id;
    private Integer userId;
    private String walletType; // "IN" or "OUT"
    private String description;
    private BigDecimal amount;
    private LocalDateTime transactionTime; // Date in string format
    private BigDecimal remainingBalance; // Unique identifier for the transaction
//    private String status; // "PENDING", "COMPLETED", "FAILED"

    // Constructors, getters, and setters can be generated by Lombok
}


